const assert=require('assert');
const {ProjectSupervisor}=require('../core/supervisor');
const s=new ProjectSupervisor();
const good=s.evaluate({id:'t1',result:'done',verification:{passed:true,evidence:{tests:'ok'}}});
assert.strictEqual(good.passed,true);
const bad=s.evaluate({id:'t2',project:'pognali3',result:'done',verification:{passed:true,evidence:{}}});
assert.strictEqual(bad.passed,false);
assert(bad.missing.includes('evidence'));
assert.strictEqual(s.shouldFix(bad),true);
const fix=s.createFixTask({id:'t2',project:'pognali3',requiredSkills:['software_development']},bad);
assert.strictEqual(fix.parentTask,'t2');
assert.strictEqual(fix.project,'pognali3');
assert(fix.reason.includes('evidence'));
console.log('supervisor tests passed');
